module R6502
  class Cpu
    def instr_mode(opcode)
    #adc
      { 0x69 => {:instr => :adc, :mode => :imm},
        0x65 => {:instr => :adc, :mode => :zp},
        0x75 => {:instr => :adc, :mode => :zpx},
        0x6d => {:instr => :adc, :mode => :abs},
        0x7d => {:instr => :adc, :mode => :absx},
        0x79 => {:instr => :adc, :mode => :absy},
        0x61 => {:instr => :adc, :mode => :indx},
        0x71 => {:instr => :adc, :mode => :indy},
    #and
        0x29 => {:instr => :and, :mode => :imm},
        0x25 => {:instr => :and, :mode => :zp},
        0x35 => {:instr => :and, :mode => :zpx},
        0x2d => {:instr => :and, :mode => :abs},
        0x3d => {:instr => :and, :mode => :absx},
        0x39 => {:instr => :and, :mode => :absy},
        0x21 => {:instr => :and, :mode => :indx},
        0x31 => {:instr => :and, :mode => :indy},
    #asl
        0xa9 => {:instr => :asl, :mode => :imm},
        0xa9 => {:instr => :asl, :mode => :imm},
        0xa9 => {:instr => :asl, :mode => :imm},
        0xa9 => {:instr => :asl, :mode => :imm},
        0xa9 => {:instr => :asl, :mode => :imm},
    #bit
        0xa9 => {:instr => :bit, :mode => :imm},
        0xa9 => {:instr => :bit, :mode => :imm},
    #bpl
        0xa9 => {:instr => :bpl, :mode => :rel},
    #bmi
        0xa9 => {:instr => :bmi, :mode => :rel},
    #bvc
        0xa9 => {:instr => :bvc, :mode => :rel},
    #bvs
        0xa9 => {:instr => :bvs, :mode => :rel},
    #bcc
        0xa9 => {:instr => :bcc, :mode => :rel},
    #bcs
        0xa9 => {:instr => :bcs, :mode => :rel},
    #bne
        0xa9 => {:instr => :bne, :mode => :rel},
    #beq
        0xa9 => {:instr => :beq, :mode => :rel},
    #brk
        0xa9 => {:instr => :brk, :mode => :imm},
    #cmp
        0xc9 => {:instr => :cmp, :mode => :imm},
        0xc5 => {:instr => :cmp, :mode => :zp},
        0xd5 => {:instr => :cmp, :mode => :zpx},
        0xcd => {:instr => :cmp, :mode => :abs},
        0xdd => {:instr => :cmp, :mode => :absx},
        0xd9 => {:instr => :cmp, :mode => :absy},
        0xc1 => {:instr => :cmp, :mode => :indx},
        0xd1 => {:instr => :cmp, :mode => :indy},
    #cpx
        0xe0 => {:instr => :cpx, :mode => :imm},
        0xe4 => {:instr => :cpx, :mode => :zp},
        0xec => {:instr => :cpx, :mode => :abs},
    #cpy
        0xc0 => {:instr => :cpy, :mode => :imm},
        0xc4 => {:instr => :cpy, :mode => :zp},
        0xcc => {:instr => :cpy, :mode => :abs},
    #dec
        0xc6 => {:instr => :dec, :mode => :zp},
        0xd6 => {:instr => :dec, :mode => :zpx},
        0xce => {:instr => :dec, :mode => :abs},
        0xde => {:instr => :dec, :mode => :absx},
    #eor
        0x49 => {:instr => :eor, :mode => :imm},
        0x45 => {:instr => :eor, :mode => :zp},
        0x55 => {:instr => :eor, :mode => :zpx},
        0x4d => {:instr => :eor, :mode => :abs},
        0x5d => {:instr => :eor, :mode => :absx},
        0x59 => {:instr => :eor, :mode => :absy},
        0x41 => {:instr => :eor, :mode => :indx},
        0x51 => {:instr => :eor, :mode => :indy},
    #clc
        0x18 => {:instr => :clc, :mode => :imp},
    #sec
        0x38 => {:instr => :sec, :mode => :imp},
    #cli
        0x58 => {:instr => :cli, :mode => :imp},
    #sei
        0x78 => {:instr => :sei, :mode => :imp},
    #clv
        0xb8 => {:instr => :clv, :mode => :imp},
    #cld
        0xd8 => {:instr => :cld, :mode => :imp},
    #sed
        0xf8 => {:instr => :sed, :mode => :imp},
    #inc
        0xe6 => {:instr => :inc, :mode => :zp},
        0xf6 => {:instr => :inc, :mode => :zpx},
        0xee => {:instr => :inc, :mode => :abs},
        0xfe => {:instr => :inc, :mode => :absx},
    #jmp,
        0x4c => {:instr => :jmp, :mode => :abs},
        0x6c => {:instr => :jmp, :mode => :ind},
    #jsr,
        0x20 => {:instr => :jsr, :mode => :abs},
    #lda,
        0xa9 => {:instr => :lda, :mode => :imm},
        0xa5 => {:instr => :lda, :mode => :zp},
        0xb5 => {:instr => :lda, :mode => :zpx},
        0xad => {:instr => :lda, :mode => :abs},
        0xbd => {:instr => :lda, :mode => :absx},
        0xb9 => {:instr => :lda, :mode => :absy},
        0xa1 => {:instr => :lda, :mode => :indx},
        0xb1 => {:instr => :lda, :mode => :indy},
    #ldx,
        0xa2 => {:instr => :ldx, :mode => :imm},
        0xa6 => {:instr => :ldx, :mode => :zp},
        0xb6 => {:instr => :ldx, :mode => :zpy},
        0xae => {:instr => :ldx, :mode => :abs},
        0xbe => {:instr => :ldx, :mode => :absy},
    #ldy,
        0xa0 => {:instr => :ldy, :mode => :imm},
        0xa4 => {:instr => :ldy, :mode => :zp},
        0xb4 => {:instr => :ldy, :mode => :zpx},
        0xac => {:instr => :ldy, :mode => :abs},
        0xbc => {:instr => :ldy, :mode => :absx},
    #lsr,
        0x4a => {:instr => :lsr, :mode => :imp},
        0x46 => {:instr => :lsr, :mode => :zp},
        0x56 => {:instr => :lsr, :mode => :zpx},
        0x4e => {:instr => :lsr, :mode => :abs},
        0x5e => {:instr => :lsr, :mode => :absx},
    #nop,
        0xea => {:instr => :nop, :mode => :imp},
    #ora,
        0x09 => {:instr => :ora, :mode => :imm},
        0x05 => {:instr => :ora, :mode => :zp},
        0x15 => {:instr => :ora, :mode => :zpx},
        0x0d => {:instr => :ora, :mode => :abs},
        0x1d => {:instr => :ora, :mode => :absx},
        0x19 => {:instr => :ora, :mode => :absy},
        0x01 => {:instr => :ora, :mode => :indx},
        0x11 => {:instr => :ora, :mode => :indy},
    #tax,
        0xaa => {:instr => :tax, :mode => :imp},
    #txa,
        0x8a => {:instr => :txa, :mode => :imp},
    #dex,
        0xca => {:instr => :dex, :mode => :imp},
    #inx,
        0xe8 => {:instr => :inx, :mode => :imp},
    #tay,
        0xa8 => {:instr => :tay, :mode => :imp},
    #tya,
        0x98 => {:instr => :tya, :mode => :imp},
    #dey,
        0x88 => {:instr => :dey, :mode => :imp},
    #iny,
        0xc8 => {:instr => :iny, :mode => :imp},
    #rol,
        0x2a => {:instr => :rol, :mode => :imp},
        0x26 => {:instr => :rol, :mode => :zp},
        0x36 => {:instr => :rol, :mode => :zpx},
        0x2e => {:instr => :rol, :mode => :abs},
        0x3e => {:instr => :rol, :mode => :absx},
    #ror,
        0x6a => {:instr => :ror, :mode => :imp},
        0x66 => {:instr => :ror, :mode => :zp},
        0x76 => {:instr => :ror, :mode => :zpx},
        0x6e => {:instr => :ror, :mode => :abs},
        0x7e => {:instr => :ror, :mode => :absx},
    #rti,
        0x40 => {:instr => :rti, :mode => :imp},
    #rts,
        0x60 => {:instr => :rts, :mode => :imp},
    #sbc,
        0xe9 => {:instr => :sbc, :mode => :imm},
        0xe5 => {:instr => :sbc, :mode => :zp},
        0xf5 => {:instr => :sbc, :mode => :zpx},
        0xed => {:instr => :sbc, :mode => :abs},
        0xfd => {:instr => :sbc, :mode => :absx},
        0xf9 => {:instr => :sbc, :mode => :absy},
        0xe1 => {:instr => :sbc, :mode => :indx},
        0xf1 => {:instr => :sbc, :mode => :indy},
    #sta,
        0x85 => {:instr => :sta, :mode => :zp},
        0x95 => {:instr => :sta, :mode => :zpx},
        0x8d => {:instr => :sta, :mode => :abs},
        0x9d => {:instr => :sta, :mode => :absx},
        0x99 => {:instr => :sta, :mode => :absy},
        0x81 => {:instr => :sta, :mode => :indx},
        0x91 => {:instr => :sta, :mode => :indy},
    #txs,
        0x9a => {:instr => :txs, :mode => :imp},
    #tsx,
        0xba => {:instr => :tsx, :mode => :imp},
    #pha,
        0x48 => {:instr => :pha, :mode => :imp},
    #pla,
        0x68 => {:instr => :pla, :mode => :imp},
    #php,
        0x08 => {:instr => :php, :mode => :imp},
    #plp,
        0x28 => {:instr => :plp, :mode => :imp},
    #stx,
        0x86 => {:instr => :stx, :mode => :zp},
        0x96 => {:instr => :stx, :mode => :zpy},
        0x8e => {:instr => :stx, :mode => :abs},
    #sty,
        0x84 => {:instr => :sty, :mode => :zp},
        0x94 => {:instr => :sty, :mode => :zpx},
        0x8c => {:instr => :sty, :mode => :abs} }[opcode]
    end
  end
end
